#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
curl localhost
sudo nginx -t
sudo service nginx reload
