#!/usr/bin/env bash
# Installing and setting up haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy

echo "ENABLED=1" |sudo tee /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                   echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 48696-web-01 54.208.215.244:80 check
   server 48696-web-02 54.144.146.48:80  check
" |sudo tee /etc/haproxy/haproxy.cfg

service haproxy start
