#!/usr/bin/env bash
# Install HAProxy

echo -e "Updating and doing some minor checks...\n"

sudo apt-get update -y -qq && sudo apt-get install -y haproxy -qq
echo -e "\n"

echo -e "\nSetting up some minor stuff.\n"

# Backup the default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define the server configuration
server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s
frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend
backend clickviral-tech-backend
    balance roundrobin
    server 151666-web-01 34.232.68.152:80 check
    server 151666-web-02 3.83.227.80:80 check
"

# Write the server configuration to the HAProxy config file
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Start the HAProxy service
sudo service haproxy start
