#!/usr/bin/env bash
# install load balancer


# Update package lists and install HAProxy
sudo apt-get update -y -qq
sudo apt-get install -y haproxy -qq

echo -e "\nSetting up haproxy server.\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend tilan-tech-frontend
    bind *:80
    default_backend tilan-tech-backend

backend tilan-tech-backend
    balance roundrobin
    server 48696-web-01 54.208.215.244:80 check
    server 48696-web-02 54.144.146.48:80  check
"

# Write the server configuration to the HAProxy config file
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Start the HAProxy service
sudo service haproxy start
